services:
  - type: web
    name: php-backend
    env: php
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t .
    envVars:
      - key: DB_HOST
        value: <localhost>
      - key: DB_USER
        value: <root>
      - key: DB_PASSWORD
        value: <>
      - key: DB_NAME
        value: <think_space_db>

